var store = require('../models/database.js')
const fortune = require('fortune')


//post generation

var data = {
  titles: [
    "Kingsman The Golden Circle  Official Trailer  0158",
    "Police Reports Blame United Passenger for Injuries he Sustained While Dragged Off Flight",
    "I proposed to my girlfriend today and didnt get to properly thank the stranger who took our picture If youre out there, I cant thank you enough",
    "Trump backs away from demand for border wall money",
    "Young Shaq brings down the hoop",
    "Worlds largest single firework shell",
    "You know youre an awful president when the Carter Library trolls you for being a failure",
    "Want a me",
    "Were at an Important Crossroad in our Lives  1239",
    "If you go to Walmart and you dont see any weird people, does that make YOU the weird person",
    "1 life down, 8 left to go",
    "TIL that Pornhub has been contributing to charity since 2012 They have ran charity campaigns that planted trees, provided free breast cancer checks and donated to panda conversation charities",
    "Be the best man you can be",
    "New foster dog, hes super sweet, but mostly blind I cant reach my coffee, or the remote, but hes finally comfortable and seems to feel secure Snore away buddy",
    "20 year old tree growing out the top of a silo",
    "My daughter is four and thinks I can fix anything",
    "Its a trap",
    "Unrepentant",
    "Territorial hippo joins brawl between wildebeest and crocodile",
    "Today in Italy we celebrate the Liberation from Nazifascism  Viva lItalia Libera",
    "Top 50 Largest Corporations by Revenue OC",
    "I ate BaconampCheddar waffle with fried chicken and a honey chili sauce",
    "PSA An official marathon of Carl Sagans Cosmos is currently being streamed on Twitch",
    "Transgender woman denied food at soup kitchen because she was wearing a dress The director said his mission was acting according to the Bible Christianity is dependent on our obedience to God",
    "The only American Idol I have ever remembered  0150",
    "Tiger Woods exwife used to be hot in the 90s, but what does she look like now  Shes still quite attractive Saved you 60 clicks Seriously 60",
    "Zen And The Art of Motorcycle Maintenance Author Robert M Pirsig Dies At 88",
    "A slur is a slur Dont matter who says it",
    "The computer running Reddits search function",
    "pollak reveals his power level",
    "Zero fucks Volibear  0044",
    "Newcastle United Have Been Promoted to the Premier League",
    "My fiance thinks that I dont know about him cheating on me My background and credit check just went through amp im moving into my new apartment in two weeks",
    "White Dragon, Kousyuuya, Painting, 2012",
    "I didnt know Firaxis loved us D",
    "My grandfather, mom, and uncle in 1939, relaxing after crossing the border out of Nazi territory",
    "me irl",
    "The future of VR porn",
    "400 hours of playing against Genji",
    "Grand Canyon lit only by the moon OC3000x2000",
    "Lowres cat",
    "Yet another nip overdose Completely unresponsive",
    "Gravity Defying",
    "hmmm",
    "What magic is this",
    "The US Embassy in the UK is promoting MaraLago on its website While Trump spends his time golfing or watching cable news, the State Department is advertising for Trumps private club in Florida Your taxpayer dollars are paying for this This is not acceptable Call your representatives",
    "I got banned from laser tag today",
    "The highest and lowest elevation of every US state",
    "A Foggy Night",
    "PsBattle Two mannequins posing awesomely",
    "I know someone whod like this calzone",
    "rthedonald, rpussypass, rconspiracy, and more are currently vote brigading, spamming, and harassing users on rSyrianrebels No admin action so far",
    "Tire meets an old friend",
    "After 15 years of hoarding fish I present the Fish Museum",
    "lt Number of people who want Le Pen to lose",
    "Mayor Taylor Says Poverty is a Symptom of Atheism",
    "Tight fit",
    "Cookiezi  HoneyWorks  Akatsuki Zukuyo Taeyangs Extra HDDT FC 9581 4 776pp",
    "You know its spring in Canada",
    "Michael Phelps",
    "When your cannon fires two cannonballs at a monster with 1 hp left",
    "Baby elephant Lia, helped by her aunt Kery",
    "The meal for kings",
    "I Should Get a Boat",
    "They wouldnt take the photo unless I smiled",
    "Weed legalization in Canada",
    "What 500 hours of Fallout 4 looks like",
    "This image pretty much sums up the state of Linux 10 years ago",
    "Funhaus dressed up as their Wwe characters",
    "Fire Emblem Heroes  New Heroes World of Radiance  0135",
    "Ad by swiss police",
    "Massdrop trolled me again I think",
    "When I was your age I only made 6hour",
    "Dear wife, if you see this",
    "When the priest brings out the big guns",
    "Think youre too old Think again Left is day 1  right almost 3 years later some makeup and a small color correction wfilter  lovingmylife",
    "MiaRand as Triss Merigold",
    "Unrollme head heartbroken that users found out it grew up fertilized in the UK is promoting MaraLago on its website",
    "Wax worms can eat and break down one of the most common plastics, polyethylene Their digestive process breaks the plastics chemical bond, producing an organic compound",
    "What 2 years of Demo Discs do to a man",
    "One of those days",
    "John Get the cement truck",
    "Blue Eyes",
    "What embarrassing moment did you not stop someone from doing because you wanted to see what happened instead",
    "Tank and Jeans On and Off",
    "Five top Game Of Thrones cast members to pocket 2million per episode in season seven and eight",
    "In the Dominican Republic Plan B is sold as After D",
    "Meet Gizmo and Gadget  they will be coming to live with us soon yay",
    "Tonights signs for RAW in KC Combining me and my girlfriends mutual love for wrasslin and Spongebob",
    "really really real",
    "Capitalism",
    "No wonder this guy has a 284 KD ratio",
    "Maybe keeping your kids out of school will cause them to develop the same stupid opinions as yours",
    "Uber cloaked its spying and all it got from Apple was a slap on the wrist",
    "It seems in your anger, you killed her",
    "Ive been a massive fan of Swamp Thing my entire life Today I was lucky enough to grab the holy grail",
    "When Reynad counters the quest",
    "Haiku Oh La La  0012",
    "me irl",
    "Hercules beetle pupa",
    "States are moving to cut college costs by introducing opensource textbooks",
    "TIL There is a white man caf in Tokyo, where Japanese ladies ring a bell to summon tuxedowearing caucasians who respond with yes, princess and serve them cake",
    "New Android Messages adds ability to add people midchat",
    "The State Department is apparently spending money to officially promote MaraLago",
    "Singleline art",
    "Selfproclaimed sociopath and sex god",
    "CINMIL Eric Thames hits home run 10 His 7th against the Reds alone",
    "Family portrait instantly improved",
    "Triss Merigold doing butt stuff MiaRand The Witcher",
    "Just ran my first mile ever without stopping",
    "Guys who go to the gym are pussies",
    "I forgot to buy bread ",
    "Anyone fans of really nice quads in yoga pants",
    "Got this just in time for Kiev Go big blue",
    "Last Video  Rest in peace, Hayven  0228",
    "The most intelligent man on LinkedIn is looking for an equally smart partner xpost rIAmVerySmart",
    "Preacher on an English nudist beach  England, 1974 1920 x 1280",
    "Our little girl turns 2 today She might be half cat",
    "Booty and Cargo Shorts",
    "Iconic",
    "We graduated almost 8 years ago",
    "2meirl4meirl",
    "Maud",
    "People keep telling me I look like a librarian",
    "Angiogram showing damageddecreased vascular tissue in the index finger of a yoyo master",
    "I live inside this string prison, now",
    "Thinking of you guys over the creek in NZ today From an Aussie",
    "Mantis Shrimp punches claw off a crab xposted from rgifs",
    "Irrelephant title",
    "Take a joke bruh",
    "Selfproclaimed Nazi Mod stickies his own comment Refuses to accept that the Jew Einstein influenced modern physics",
    "I gave masking a try what do you guys think",
    "A completely accurate analogy",
    "Also can i see your boobs",
    "63 pics in album My Korean War colour album WARNING NSFW",
    "Royal Rumble time Ill finish him with a flip from the roof , wearing a gorilla suit seriously, WCGW",
    "Making a playlist for the PCMR Birthday Party this Saturday",
    "Fuck Tammy",
    "AMA Request Someone involved in recording or inserting appropriate words in Rrated movies to make them OK for TV",
    "Why",
    "Respect my authority, puppy style",
    "Most impressive use of Theremin I have ever seen  0248",
    "US Gremlins 1984 A man brings home a cute creature as a Christmas present for his son that spawns a horrifying army of devilish  and dangerous  little beasts",
    "Saoirse Ronan",
    "More GOP politicians have been arrested for sexual misconduct in bathrooms than trans people",
    "When Timmy came home from the playground and asked what flaccid meant, Brenda and Will struggled to come up with SFW visual aids",
    "The mad bartender xpost from rMorrowind",
    "If you want to face me, youll have to pass through my five underbosses",
    "meirl",
    "BotW Animation comparing the world map of Breath of the Wild to some other games",
    "Train Wreck In Paris, France  1895",
    "The James Webb Space Telescope would like to make a special shoutout to the coolest sub on reddit",
    "Take the mic",
    "LPT Always let a dog sniff your fist first before trying to pet him, then scratch under the chin and on the sides Never reach or stand over a dog Reaching over top a dogs head can be threatening",
    "Its confederate memorial day Lets celebrate with the only confederate flag that matters",
    "HMB while I finish this Wrestling match",
    "Met Alan Tudyk yesterday, he signed a watercolor I painted for my husband",
    "OT One of the most beautiful racecars ever The Bentley Speed 8",
    "Entire US Senate to go to White House for North Korea briefing",
    "Fuck the border wall",
    "I actually agree with this one",
    "News Pangu Jailbreak iOS 1031 on iPhone 7",
    "Teaching kids the harsh reality of life",
    "A weird place I found while exploring the forest near my city 2448 x 3264 OC",
    "Shroud getting real",
    "Big Dick Treat For Hyper Cutie",
    "Lots of people have pmed me for links and info on 426 In an effort to cut down on clutter in the sub, here is ALL relevant info I have compiled on 426 related events",
    "A clean, modern, interactive periodic table",
    "I LOVE THIS SITE",
    "Taking Back Sunday  MakeDamnSure Punk Rock  0335",
    "So atmospheric CO2 levels just reached 410 ppm, first time in 3 million years its been that high What happened 3 million years ago",
    "Member when you saw this and actually thought you were doing something wrong",
    "Attending to an annoying cellmate",
    "Showing tattoo",
    "Another one of my wifes paintings of Mew and Mewtwo, what do you guys think ",
    "46 Countries Offer Free Contraceptives but Not The United States",
    "Modpost NMD Lanyard GIVEAWAY",
    "RutHlEsS OwNEr RiPS TOngUe FrOM PoOR caT",
    "Lava hits the sea in Hawaii L",
    "Let me give you a hand with that",
    "Come at me BtCH",
    "What does 80 year old vagina taste like",
    "Woman crossing the street",
    "Corporate Lobbyists turned BC Liberal candidates",
    "This pointy thing is evil",
    "Amidst Backlash, Ivanka Trump Clothing Is Secretly Relabelled as Adrienne Vittadini",
    "You gonna eat that",
    "I made a GIF to compare the world map of Zelda Breath of the Wild to Skyrim and some other maps Based on data by uHylianWarrior",
    "Oh the joy",
    "Hecarim by Dante Liu",
    "In light of a possible US government shutdown",
    "HMF while I give her some Sweet Shin Music",
    "When Link pauses to eat in battle, I imagine him holding up a finger ala Archer",
    "PIC",
    "DONT CHALLENGE TIPPA BECAUSE YOULL NEVER WIN",
    "Cub attacked by scallop",
    "Going commando on the street GIF",
    "PRAY FOR EVEREST ",
    "My sunflower tattoo done by Rodd Diaz from Lucky Bird Tattoo in Annapolis, Maryland",
    "Never change, Nick",
    "50 Years Ago, This Was a Wasteland He Changed Everything 2017  Fried chicken tycoon David Bamberger devotes his life to restoring degraded landscape  National Geographic, 8 min  0817",
    "Hair Up, Girls Out F",
    "How do you like my first pelfie",
    "Critics discussion",
    "Trump boasts of highest TV ratings since the World Trade Center came down",
    "ELI5 Whats happening when you take a pill, but it feels like its caught in the back of your throat",
    "Prosecutors Inmates water cut off for 7 days before his death in the Milwaukee County Jail",
    "When you already know that youre going to get another Emmy",
    "WDYWT prom saturday",
    "YOU VERSUS THE HUMAN SHE TOLD YOU NOT TO WORRY ABOUT",
    "Dont vaccinate your kids, you will save money when they dont live long enough to go to college",
    "",
    "animeirl",
    "MRW I sent a dick pic to a blind girl OC",
    " Just a lit touch",
    "Here comes the child bride",
    "The worlds first vaccine against malaria will be introduced in three countries  Ghana, Kenya and Malawi  starting in 2018",
    "The rmalelivingspace starter pack",
    "Rosario Dawson looks luscious",
    "Open shirt",
    "Cats have a special purr that they use with their caretaker when they want food It has a higher pitched component than other purrs",
    "Ashley Alban  A Few Inches At A Time",
    "Blizzard Is Currently Working on 3 New Maps for Overwatch",
    "This B R A V E B O Y E dun first boop with vv big snoot cowpupper  13 weeks",
    "Do you want ants Cause thats how you get ants",
    "I took a minor spill biking in to work this winter, and tore small whole in my jacket My friend just patched it up for me Im very happy with what she did",
    "The Worlds Best Chicago Comic Con Costume In The World",
    "Anya amp Aaliyah",
    "My crabapple right now",
    "Is it me, Jesus",
    "Chef told one of our pizza cooks he could paint the walk in door, this was the result",
    "rdeler suchen eine Wohnung",
    "WHO LIVES IN A TEUFORT UNDER THE SEA",
    "See what happens when you push me down in the dunk tank one too many times",
    "Taking advantage of drunk friend who can barely sit up",
    "New meme template, has a lot of controversial potential, BLSH",
    "Ask Jeeves",
    "Modern take on a rustic kitchen in this cabin located in Montana 2048  1360",
    "Register the  symbol as a trade mark sit back and count the money from lawsuits",
    "NA Legacy Client Now Retired",
    "My hats, past present and future",
    "Does Donatello deserve to be a Ninja Turtle",
    "Ribs amp Fries 1080x1349",
    "Arin, you gotta cut that hair back down, brother Look at this sex machine",
    "out this field",
    "Getting Split Roasted By My Boyfriend And His Virgin Friend",
    "Do it for Kerr",
    "hey goo, whats new oc",
    "Lava hits the sea in Hawaii",
    "Coming down the stairs with his prom date",
    "Showgirls Play Chess Backstage at the Latin Quarter Nightclub Gordon Parks, 1958",
    "Be careful who you call ugly in middle school",
    "Amazing Android 18 fanart by sakimichan on deviantart",
    "Cool things I see at work 1944 Enfield No4 Sniper",
    "Im Steve Huffman, programmer and Reddit CEO AMA",
    "Milf step mom opens legs for step son",
    "Hot Latin girl and her amazing body get dicked",
    "waiting",
    "Let me give you a hand",
    "Chef who is a fan of Chos fixes her a free meal",
    "When you get stuck in barbed wire on Battlefield 1",
    "For the Love of God, no one cares if you were Banned from rSocialism or rConservative",
    "I honestly dont even understand this fucked up shit",
    "Mesmerised boopstroke",
    "Im sure its just a fluke",
    "So accurate",
    "All life is precious",
    "Me and my hitachi IRL",
    "Nautilus table by Marc Fish 800x533",
    "Too chill for thrill",
    "Cat",
    "Please dont recruit anyone Explanation inside",
    "Flying is a skill which comes natural to snow leopards",
    "Hand feeding an apex predator that lived through the KT extinction",
    "Nag nag nag",
    "Is rAll trying to say something",
    "Creaming Hard",
    "First time posting here, hope you enjoy this clip from last night",
    "TIFU by sending the Navy Seal copypasta over live chat to a company whilst at college",
    "Internet Archive announces will ignore robotstxt",
    "Emmpot",
    "Ermmight as well suck it I guess",
    "lt number of people who want to see h3H3 open their Patreon back up so we can support the hell out of them in this trying time",
    "Thousandhand Bodhisattva dance",
    "Girl from Japan battles big handrail",
    "Someone at work kept touching my stuff, so I left a note",
    "rWholesomeMemes coming through once again",
    "Yes, why dont I upvote every post in rfunny",
    "Scalloped corn with snake",
    "Redditor concisely breaks down the foam vs paper cup debate in response to a note written on a Dunkin Donuts bathroom hand dryer",
    "So I just found this amazing spot",
    "She wont let it touch the ground",
    "Lilly Ford Takes Massive Cock",
    "Saw a few pics in this style here Gave it a try with this shot I took in Osaka",
    "Velour",
    "Shaolin soccer in real life",
    "The 203s are hot 1000x667",
    "Took 3 refugees to Disneyland, story in the comments",
    "The Danish Language",
    "A Glitch in the Frontier The Patch Notes",
    "Riverbank in Limerick, Ireland OC 4000 x 4000",
    "Perfect form caught in slo mo",
    "Did drawing of Master Chief digitally on my iPad",
    "woof irl",
    "Six months of not believing Life is beautiful",
    "What song do you listen to, to check the quality of new headphones",
    "Should be fine",
    "Anon witnesses weird shit",
    "Saw this in house listing What kind of refrigerator is this",
    "USAOC The Ultimate Reverse of Shame  0149",
    "Coming down the stairs with his prom date",
    "April Contest Egg ruins everything",
    "Nichole Bloom Shamless",
    "SUGGESTION Players who knocked down the enemy should get the kill, Not the player who finished it",
    "These frozen peas in the shape of a frozen P",
    "Im not in TEST, but I crocheted a uCymek dino",
    "Factorio 0150",
    "Heart shaped pupils",
    "Someone thought this ramp was a good idea",
    "Watch Until The End  1258",
    "Heath Ledgers sister clears up rumour linking Joker role to actors death at I Am Heath Ledger premiere",
    "Nice",
    "Boobs are fun",
    "Salmon Cannon Xpost from Gifs",
    "My first attempt at Unicorn Cupcakes",
    "Self My Negan Cosplay for Awesome Con and New York Comic Con 2017",
    "Blep",
    "Delicious goodness",
    "For honor new map leak",
    "Aggressive Driver Karma  0119",
    "As an Australian born Assyrian, if it wasnt for this man who rescued 50,000 Assyrians from genocide during World War I, I would not be alive Lest We Forget Lt Gen Stanley Savige",
    "One both cant what",
    "My girlfriend sent me a picture of her client, Winston",
    "Sharks at Fingal Bay",
    "Looks like somebodys got a case of the Mondays",
    "12 day old beans",
    "Former Mrs Orange County pleads guilty to possessing child pornography",
    "Noticed a peculiar coincidence about Frances election map 708 x 473",
    "Got drunk Stole a random street sign",
    "OC In an attempt to direct my murder hobos",
    "Breasttaking",
    "Blue Thong",
    "Oh, you",
    "Morgan Reid",
    "Trumps borderwall fantasy is crumbling",
    "Begging for it",
    "If in Washington DC, I cant recommend enough swinging by the UdvarHazy Air and Space Museum Right by Dulles airport, its crammed with planes and spacecraft, from the Enola Gay to the Space Shuttle Discovery",
    "toomeirlformeirl",
    "My girlfriend was just messing around drawing random things before work and came up with this image of Michael Myers that I figured some people here might appreciate Considering the short amount of time it took her to draw it I was very impressed",
    "Painting my R3 matte white",
    "Congratulations, rTheOcho You are Subreddit of the Day",
    "New Pet",
    "Kendrick Lamars Humble Hits No 1 on Billboard Hot 100",
    "One of those days",
    "Package from Xbox Design Lab came in, introduced it to the fam",
    "Indian style",
    "overwhelming response with the last one, heres another Brach aircancel",
    "Attack commences in 30 seconds",
    "Girlfriend wants to show off some more What would you do to her",
    "Before After",
    "Florida Man, 73, punches cop, shouts Im a grown fckng man",
    "SORRY MFERS I DONT HAVE ANY PHOTOSHOP SKILLS SO THIS IS HOW I DELIVER",
    "Your arrogance blinds you, special needs kid",
    "Meowirl",
    "Beautiful Orgasm",
    "just perfect",
    "During the 16 season, DOnta Foreman experienced an unimaginable loss The passing of his son, DOnta Jr",
    "Hamox",
    "Companies who give candidates homework assignments knock it off old but still relevant",
    "Our Dev Team vs Their Dev Team HOTS vs Hearthstone",
    "Imagine getting used to privilege so much",
    "First night home from the shelter with a cut up nose vs this weekend napping on her favorite blanket",
    "Incredible but humble woman on DeviantArt was a child prodigy, fought in the US Special Forces, has degrees in three different fields, is descended from Spanish nobility, has met the Pope, has been on television numerous times, owned a house when she was 16 years old, and much more",
    "I tried to be unique in college class field with cute girls",
    "f On and off",
    "Fluttering Faye",
    "Vem r du",
    "Using her drunk friend",
    "The Apprentice Official Audio  0356",
    "Hesarilla riitt huumorintajua",
    "Goddamnit Barry",
    "ModF4NV New Vegas in Fallout 4 Walking from Goodsprings to Primm",
    "The DMV requires a lot more time than the time it takes for my clothes to come off ",
    "A chicken gets to fulfill her dream of flying  0108",
    "As US prepares to gut net neutrality rules, Canada strengthens them",
    "Monstrous",
    "Collecting the leaking doggystyle creampie in my panties Big load",
    "A response to the selfie debate prior to professional shoot",
    "When your SO combines two of your favourite pastimes Got me all Sanjid up in appreciation",
    "We out here boys",
    "Stay out of my personal space",
    "My girl found these on the ground sealed",
    "My fiance has kept this for 22 years and will finally redeem it this weekend",
    "TIL that angry Birds are quadrapedal",
    "Snapchat needs to make this Donald Trump filter permanent",
    "Ive been itching to doodle Palla for awhile so here she is",
    "Why is everyone upset about American Airlines and the stroller video",
    "Thanks EA",
    "The Holocaust Who are the missing million",
    "Petit rappel",
    "TIL Dr Seuss wrote Green Eggs and Ham based on a 50 bet he couldnt write an entertaining childrens book using only 50 words",
    "Perfection",
    "Trump admin considering elimination of tax deferred 401k to pay for business tax rate cut",
    "Im out",
    "Ouija, youve helped us so much, answered so many of our questions  tell us, what can we do for you in return",
    "Thick cum on amateur brunette",
    "New York a few years from now  1881",
    "They havent even begun to peak",
    "R6SiegeBroken Legs",
    "Ethics Huffington Post Editor Resigns In Shame Over Hoax Article That Said White Men Shouldnt Get to Vote",
    "Humour Even the nicest of people have limits",
    "",
    "Enjoying a day off finally",
    "Portland Trail Blazers Appreciation Thread",
    "Free black walnut anyone",
    "One reason I dont do risky activities is because, if I die, my dogs wont understand why I never come back",
    "Making fluorescent nylon",
    "More than three months after Senate Intelligence Committee launched its investigation into Russian meddling in the 2016 election  the panel has made little progress and is increasingly stymied by partisan divisions that are jeopardizing the future of the inquiry We need an Independent Commission",
    "Lake Marie",
    "Sure thing",
    "Me irl",
    "The Reich Stuff",
    "Tims Saving Kuku",
    "Looking For Friends Konosuba xpost rKonosuba",
    "I Found Andys Spotify Playlist",
    "Your balls are showing",
    "Theres no way, right",
    "My wife is apparently friends with enemies of the state Please advise",
    "Stopped Talking  for three days",
    "Trying to cover up her naked body in public",
    "HYUKOH  Wanli  0513",
    "A study break that went on for too long",
    "I adopted an overweight dog Heres a before and after pic of him losing 9 pounds",
    "This is so funny",
    "Caribbean Jerk Chicken with pineapple on Jasmine rice in a pineapple bowl for your Monday Homemade",
    "At 23, Ive fulfilled a life goal by purchasing my first PC",
    "Seen NTU",
    "Noras New Style Mojojoj",
    "Kripp will hit the button at 1 million followers",
    "Hoe life",
    "They say you are what you eat",
    "Team Trump lacks the experience to fulfill promises This has been amateur hour at the White House, Elaine Kamarck said at a panel of Brookings experts on President Trumps first 100 days He didnt come in with any government expertise and he hasnt shown an interest in learning",
    "Pagani Huayra La Monza Lisa OS3064x1368",
    "Doors in KSP",
    "Kekistani soldier battle equipment",
    "Private Snap",
    "Classic lmao ",
    "Cant think of title, as heres my nipples ",
    "Triss Merigold",
    "Marine Le Pen steps down as leader of National Front party two weeks before French Presidential election",
    "Asking for gear in Nighthold",
    "Cute Asian with a Hint of Cleavage",
    "April 24 Banned and Restricted Announcement  Legacy Top banned, Vintage Probe Gush restricted",
    "Coming down the stairs with his prom date",
    "Oh no they didnuhn",
    "Its nice to know the Glorious Fire Nation is using the superior siege engine",
    "Wobble Wobble Wobble  0037",
    "Outlast 2CODEX",
    "Its treason then",
    "image this hedgehog is cheering for you , because you can do it",
    "its all yours for the taking",
    "Flare",
    "That day Jack was given a grim reminder",
    "This chewbacca sock",
    "Testify",
    "Anyone else getting suspicious about Raw Spoilers",
    "Made my girlfriend a playlist",
    "The reason Nina turned around",
    "My Nama Je",
    "British afternoon tea, delicately served on a miniature picnic table",
    "Cookiezi  supercell  My Dearest Last Love Yukiyos ver HDDT 9839 FC  675pp 1",
    "I just started currently level 22 and Ive got to say, I like the gun play but I have no idea whats going on with this story",
    "KONO OZYMANDIO DA",
    "The year my father got my mother a hoover for Christmas 1984",
    "Thought of a meme last night",
    "The shrinkage is real, length check",
    "Molly Tilove",
    "Hot Wendys girl NSFW",
    "Today this guy at work asked me for a cigarette lighter",
    "DVa getting fucked in the arcade Yeero",
    "Mayor Kenney Pa should legalize marijuana like Colorado",
    "Incapable of meeting strangers on FacebookYOU must be on your period",
    "Generous servings",
    "Medical advice to all Ketoers no, its not what you think",
    "Rocket turning into a shuttle while in orbit",
    "Finally received my Tee Fury Tee of The Day after waiting 4 weeks ",
    "Helm of Raedwald",
    "Dont you wish Melbourne, Florida didnt exist",
    "Why bang doesnt have any new disciple",
    "Found this day one when the game came out, still relevant 4 years later",
    "Found on the front page of rfunny Reddit is no better than 9GAG",
    "Poetry How to start a protest at UC Berkeley  0022",
    "Just roll with it",
    "Whenever I get a stack of resumes, I throw half of them in the trash",
    "The striking technique of Cindy Dandois",
    "Bills declined to match twoyear, 64 million offer sheet that RB Mike Gillislee signed with Patriots, per source Gillislee now a Pat",
    "The Absurdity of The Freeswag Movement  3012",
    "Just a little bun",
    "Tight ass For spanking, long hair for pulling",
    "UKIPs controversial FGM policyproposed by Diane Abbott in 2014",
    "Something really strange happened to me in pools at CEO Dreamland",
    "Yuudachi Bikini KanColle",
    "Salmon Cannon",
    "Denver marijuana shops have won permission to stay open until 10 pm",
    "534 days and counting Astronaut Peggy Whitson breaks US space record",
    "Eleven OC",
    "Just when you think",
    "China, India Become Climate Leaders as West Falters",
    "Kief Catcher Closest Thing Man Has to Savings Account",
    "Thats some serious eye contact",
    "Life Support",
    "Hitdog professional displays his skill to an unaccustomed target",
    "Cathy, I have absolutely no idea how you got this number",
    "THE END",
    "Update A classmate of my daughter 13 sent her an extremely sexually aggressive and inappropriate message via facebook messenger and I need some advice",
    "Does a beer in the bath still count NSFW",
    "Are all the oceans level with each other",
    "BART takeover robbery 50 to 60 teens swarm train, rob weekend riders",
    "Too Cute",
    "Hot Pink",
    "Pretty blonde",
    "The SU Community about the second, happy fun times promo for this bomb",
    "Strawberry Greenhouses",
    "This is why I Bitcoin",
    "Texas is such a better city than Detroit and heres why",
    "42 Yards No problem",
    "Theres nothing fucking interesting about this photo",
    "Need I say more ",
    "MRW Im the only person in the choir that didnt know we were going to sing in a higher pitch than usual",
    "Having fun bouncing in this lingerie",
    "Pair statue of Ptahkhenuwy and his wife, Egyptian, Old Kingdom, 24652323 BC 1212x1600",
    "Pro Mode is extremely helpful for tricky shots",
    "Forget Lucio, this is the new jam",
    "Lest We Forget",
    "Ronnie OSullivan asks referee what the prize money for a 147 break is after potting just two balls He then goes on to make the 147 in spectacular fashion  0856",
    "Mount Splashmore",
    "Janice Griffith gets an Adams apple",
    "Dont let her selfrape her sin cave",
    "Towering Genius disdains a Beaten 1200  900 Abraham Lincoln",
    "Deadmau5s put Sauron on one of his helmets It looks pretty cool",
    "Miranda Kerr",
    "Newcastle Utd Have Been Promoted to the Premier League for the 201718 Season",
    "Franco Noriega, a Peruvian chef",
    "Custom Westworld cameo in new commercial  0031",
    "the end",
    "Alexa Pearl",
    "The Burbs 1989 811 x 1078",
    "SB Tactical ATF reverses opinion letter that shouldering your brace redesigns your firearm",
    "Stop Using Unrollme, Right Now It Sold Your Data To Uber",
    "While everyone is obsessed with that Unicorn Frappuccino, I get to have this Unicorn Mirror 13",
    "Who wants to be my player 2 f",
    "Hercules Beetle Pupa",
    "PH My dads house is being taken away this July due to being unable to pay the mortgage He is unemployed and does not have any form of income",
    "I thought he just liked cutoffs",
    "someone come snuggle",
    "This mlem is the best mlem",
    "After a long, hard road I am finally an American Citizen This is the only country I would fight for and die for It is the only country I want to live in What was my first act as an American Citizen I registered to vote",
    "Miranda Kerr",
    "Shitpost Coming to this sub after being away for a day",
    "The most intelligent man on LinkedIn is looking for an equally smart partner",
    "Mate snagged an ultimate meme name while we were camping",
    "TCG Exclusive XYZ Tornado Dragon",
    "Rockets CEO Tad Brown 1 beer, 1 hotdogs, 1 nachos and 1 soda at Game 5",
    "Alicia Napoleon, Professional Boxer",
    "And to think we had doubts about these two",
    "Weird for its time The 2004 Lotus Espirit, the last mass produced car to feature pop up headlights",
    "Spotted in Penticton, BC",
    "Donald Trump announces 20 per cent tariff on Canadian softwood lumber",
    "My grandfather took this from a Japanese soldier that he killed in Okinawa in 1945, after he was stabbed in the shoulder with a bayonet He passed away in 2011 and said he wondered what names were on it, or who the man was Can anyone help",
    "I made a friend in the garden the other day",
    "Looking for a rich boy to support my expensive drug habit",
    "CNN Opinion Berkeley has become the most intolerant place in America",
    "Jimmy Wales goes after fake news with Wikitribune  a crowdfunded site for reporters",
    "China bans religious names for Muslim babies in Xinjiang List of banned baby names released amid ongoing crackdown on religion that includes law against veils and beards",
    "This Toronto Maple Leafs fan knows what its all about",
    "Gummy bear pyramid",
    "Old Man Casper loves his dad",
    "Karina Elle",
    "MeanwhileIn Malenas Bedroom",
    "Blonde in the style of DAMN by Kendrick Lamar",
    "Catching up on Doctor Who and my 3 yr old plops down and has been glued to the tv since the episode started Victory",
    "A candle that can burn 144 hours",
    "After screen printing for a year, I had my first gallery show",
    "Tina Louise",
    "Having fun bouncing in this lingerie",
    "Veggie Dumplings with Easy Peanut Sauce",
    "A mod of rCringeAnarchy and a user get into a plugta about a Jewish scientist That mans name Albert Einstein",
    "I think this choker really suits me F",
    "Damn, he even took the shoes",
    "Comaron the Hedgehog",
    "Modern cities in a nutshell",
    "Cute title that catches your attention F",
    "I did a thing",
    "Work of the great Pawel Kuczynski",
    "Need Deck help for Leovold",
    "Good Morning",
    "Eliza Dushku To Star In The Black Company Series Adaptation In Works By IM Global amp David Goyer",
    "SariaSkella",
    "perfect boobs",
    "Undie Monday",
    "Rachel McAdams",
    "Terrific Tessa Fowler",
    "HMRB its bobsled time",
    "What were you doing the day you realized you needed to buy a strapon",
    "My brand new camping tattoo",
    "My thick wife",
    "I wander the streets of Toronto at night, looking for cinematic moments This is what I found",
    "Building a Dobsonian telescope with John Dobson himself 12830  012831",
    "Making Copies",
    "Husky pupper climbing up a staircase",
    "To keep EpiPen sales up, Mylan threatened states, sued making bogus claims",
    "MRW Im joining the military because I have no idea what to do with my life and I realise what a stereotype I am",
    "7 years practice part 3",
    "2000year old olive tree in Bar, Montenegro",
    "MoTHEr oF ChILD FiNDs a mORbId GoRe muRDer sitE aND LOveS It",
    "My whole life in the hand of God",
    "Mike Bloomberg, Carl Pope say jobs come from clean energy, not coal",
    "Hearing Is Set for Sanders Supporters Suing DNC",
    "30plus20 We had a fun night out Then it was time to set the girls free for a fun night in ",
    "How do they feel",
    "Every parent should be so cool the world would be a better place",
    "NRA files lawsuit challenging Californias Assault Weapons Control Act",
    "64 or 32 bit Thats none of your bitness",
    "In 13 hours we will find out which nations have qualified for the Overwatch World Cup",
    "A Floating Market",
    "Salmon cannon",
    "After the war, even Franks best friends couldnt snap him out of it",
    "Fan Contest Winner Playing in the shower ",
    "Unexpected item in Wilko this weekend",
    "P120 Malakhit Target amp 3S90E Shtil",
    "She can fuck my ass anytime",
    "Fan Content Awesome Korrasami Picture",
    "Hearing Is Set for Sanders Supporters Suing DNC",
    "Rohit Sharmas midrun tantrum costing him his wicket  IPL 2016",
    "Austrian farmer finally fulfills chickens dream of flying  0108",
    "verification",
    "Photo of an enthusiastic Adolf Hitler, taken moments before ending his 6 million killstreak on Call of Duty 1945, colorized",
    "Bom 25 de abril",
    "petite body under huge scrubs",
    "I saw a guy face down on the sidewalk",
    "Wrong Species, Mate",
    "My old man and I in Ghana Whats up fellas",
    "Hercules beetle pupa",
    "One of those days",
    "Backside",
    "Opwillem voor dit chocoladebeeld van onze almachtige koning",
    "When you close and have to open the next day",
    "So I saw someone get arrested today",
    "Motor monday",
    "This is 8 week old Gracie after her first bath",
    "Elmo really shouldnt play doubles",
    "Countrystyle gatekeeping xpost rpussypassdenied",
    "Touchy Feely",
    "Girlfriends Engaged Friend MF",
    "5050 Until Dawn cosplay babes touch each others asses for fun semiNSFW  Gruesome leg break on trampoline NSFL",
    "R2D2 is almost here",
    "DeMarcus Ware Ceremonially ReSigns With Cowboys To Retire in Dallas",
    "The guy that pretended to be my father",
    "Some rope and cuff fun",
    "Visto en rpoliticalhumor",
    "What if unlocked doors had no player collision",
    "Simple song they said Still Alive  Portal, programmable speakers  0315",
    "Rafa Benitez and Newcastle Have Secured Promotion",
    "Star Child, Part 13",
    "18 year old Polina Malinovskaya",
    "Fill me up, I want a good fucking",
    "Hair Pull",
    "ccc",
    "title",
    "This titles pretty unoriginal but my comment will be better",
    "We are in Season 7 and MSI is still bo1 Isnt it time for a change",
    "Fernando Torres  Five years ago today",
    "Good news The new Caye  Dacia Duster is coming",
    "We werent imagining it we just lived through Seattles wettest FallWinter period on record",
    "I like it stolen from Crackedcom",
    "Guvernatorul Deltei Dunrii care l criticase pe Dragnea pentru partida de pescuit a fost demis din funcie",
    "Sergio Romo receives huge standing ovation in his return to ATampT",
    "Night Time Stroll",
    "Despite Hype, VR Investment Fades In Q1 2017",
    "I found an EVIL planet Extreme, lethal atmosphere, covered in giant predators More pics if you want em",
    "Canoodling via rgifcest",
    "The Doors of Kerbal xpost from rgaming",
    "My Cat REALLY Likes the Sink",
    "Look at how beautiful I am compared to the Jews",
    "Ladies ",
    "Nico Faye is red hot",
    "hmmm",
    "Bom Dia PE",
    "is fashionable scarf no is fashionable snek",
    "wiggle wiggle",
    "Im 31 and wasnt allowed dogs when I grew up Meet my first puppy, Broly",
    "Was told I should post our Maine Coon over here He just turned four",
    "Zoe Clark Hits a high note",
    "BART takeover robbery 50 to 60 teens swarm train, rob weekend riders",
    "Cum valley",
    "This cozy openair bedroom at an eco lodge in KenyaOS4146x2705",
    "Still one of my favorites",
    "Tight amp Tanned",
    "The merge of LLVM 40 into Rust has finally happened",
    "Ryukos smile",
    "More of a shake than a bounce, but still",
    "The Soyuz MS04 rocket launches from the Baikonur Cosmodrome in Kazakhstan on Thursday, April 20, 2017 carrying NASA astronaut Jack Fischer and cosmonaut Fyodor Yurchikhin into orbit to begin their four and a half month mission on the International Space Station 1041  929",
    "unsubs",
    "Thats just brutal",
    "Please dont ever stop petting me",
    "It would be a shame if everyone was reminded on Armenian genocide remembrance day that the young Turks is named after a regime that killed 15 million Armenians and the owner cenk is a vocal Armenian genocide denier",
    "Barbara  10 hours drawing, Ruslan Pronin, Digital, 2016",
    "Getting ready for the needed shave",
    "She can fuck my ass anytime",
    "Just getting a drink from the vending machine",
    "Entitled Lady doesnt care if you dont work here anymore",
    "Science AMA Series Im Beau Lotto, a neuroscientist who specializes in the biology and psychology of perception I just wrote a book called DEVIATE about the science of seeing differently and am here to talk about it AMA",
    "Donald Cerrone goes Super Saiyan",
    "Lana",
    "I made the Honey Garlic Chicken from the showing off thread ",
    "Tan lined titties",
    "Vive Le Pen",
    "Vega will be ready this quarter  AMD  Facebook",
    "Confident",
    "Intel hid this job posting in obscure location so nobody would apply plans to hire overseas for the position",
    "Used my Green Painted Endo as a Green screen",
    "Der Portalwerfer",
    "IU",
    "Quite a lineup",
    "Taking her seat",
    "Kirara   ct16041  ct16031 Electronic 2017  0746",
    "Up Close",
    "2B in Vks",
    "Superb owls are frens, not food",
    "The FTM equivalent of touching your HRT given boobs",
    "When the pets are just too good",
    "Took Reddits advice and tried to reboot my pup",
    "Im going to steal my roommates cat",
    "Roses are red, everyone needs a friend,",
    "Cameron Canela 89 pounds of fun",
    "rtheDonald At the moment",
    "Voters Confront Democratic Senator About Medicare For All and REFUSE to Back Down  1415",
    "Legendary armor concept art any weight"
  ],
  tags: ['funny', 'wtf', 'video', 'news', 'worldnews', 'tech', 'technology', 'gaming', 'music', 'iCantBelieveItsNotButter', 'nottheonion', 'makesyouthink', 'deepthoughts', 'cosplay', 'apple', 'microsoft', 'smash', 'oskdrp'],
  /*
  users: [
    "cybermage",
    "Blackbeyond",
    "TypicalGentleman",
    "jokinglyserious",
    "cyanocittaetprocyon",
    "Whoshabooboo",
    "SquaggleWaggle",
    "cereal-reposta",
    "flyoverthemooon",
    "The-Sublimer-One",
    "Luke_Boydstun",
    "RespectMyAuthoriteh",
    "airawear",
    "mar10wright",
    "Spudzydudzy",
    "DriftN2Forty",
    "BreakYourselfFool",
    "_NITRISS_",
    "PollyannaBites",
    "SeriesOfAdjectives",
    "JoeFalchetto",
    "datashown",
    "LJ_909",
    "HalfAlive_",
    "drewiepoodle",
    "malacide",
    "prpldrank",
    "SonBabel",
    "robinson217",
    "microimperetive",
    "Mrman53",
    "boohberg",
    "Myproblemsseemsmall",
    "thesadgf",
    "aloofloofah",
    "OGKnz",
    "dFpiuwhiPvv2J1DnJ",
    "chaosfreak11",
    "SwageMage",
    "pillowhands1246",
    "whatduhh",
    "Protophobic",
    "illiput",
    "Wolverine_Champ",
    "BillBrasky55",
    "DankFedoraCollector",
    "IHaeTypos",
    "blazingminer14",
    "SallyYatesIsAHero",
    "blackbrandt",
    "FoxyFoxMulder",
    "nature_fiend",
    "csockey",
    "Lupia_",
    "75000_Tokkul",
    "arska0",
    "rock_buster",
    "EldritchMayo",
    "addpulp",
    "shiballoma",
    "Stratosphere665",
    "Canaris1",
    "XaviVamos",
    "Uwat123",
    "Boygos",
    "love_the_heat",
    "ny2la",
    "BillBrasky55",
    "Patsatron",
    "fernguts",
    "IdentiFriedRice",
    "xj4me",
    "bravosix644",
    "Fishbulbz",
    "vinz243",
    "ColossalKiwi",
    "ciprian1564",
    "minniespie",
    "MisterLite",
    "Older_Wiser2",
    "Valtermann",
    "all-top-today_SS",
    "recentfish",
    "Schnitzelmann7",
    "SimonTrip",
    "Oblivion_Wonderlust",
    "_animalchin_",
    "iBallerPT",
    "PunkBiBiBi",
    "vladtud",
    "muzuzu",
    "kbmagic",
    "proud_new_scum",
    "drdangledong",
    "MeanLeanKeane",
    "MCruben3k",
    "Juball",
    "dbz2k",
    "Joeobo",
    "RONALDROGAN"
  ],
  userIDs: [],
  generateUsers: function(){
    for(var i = 0; i < data.users; i++){
      store.request(
        {
          method: fortune.methods.create,
          type: 'user',
          payload: [{title: 'hello, world', OC: false}]
        }).then(result => {
        console.log(result)
      })
    }
  },
  */
  generatePosts: function(){
    console.log('hello, world')
    for(var i = 0; i < data.titles.length; i++){
      var OC = Math.random < 0.5
      var post = {
        title: data.titles[i],
        OC: OC, 
        url: OC ? null : 'http://google.com'
      }
      console.log(post)
      store.request(
        {
          method: fortune.methods.create,
          type: 'post',
          payload: [post]
        }).then(result => {
        console.log(result)
      })
    }
  },
  generateTags: function(){
    for(var i = 0; i < data.tags.length; i++){
      store.request(
        {
          method: fortune.methods.create,
          type: 'tag',
          payload: [{name: data.tags[i]}]
        }).then(result => {
        console.log(result)
      })
    }
  },
  generatePostTags: function(){
    store.find('post').then(results => {
      var p = results.payload.records 
      var ids = []
      for(var i = 0; i < p.length; i++){
        ids.push(p[i].id)
      }
      return ids
    }).then(posts => {
      store.find('tag').then(results => {
        var t = results.payload.records 
        var tagIds = []
        for(var i = 0; i < t.length; i++){
          tagIds.push(t[i].id)
        }

        console.log('posts: ' + posts.length)
        console.log('tags: ' + tagIds.length)
        for(var i = 0; i < posts.length; i++){
          var numTags = 1 + (Math.random() * 4)
          for( var j = 0; j < numTags; j++){
            var postTag = {
              post: posts[i],
              tag: tagIds[Math.floor(Math.random() * tagIds.length)],
              upvotes: Math.floor(Math.random() * 1000),
              date: new Date(Date.parse('Apr 24 2017') + Math.floor(Math.random() * 259200000))
            }
            store.request(
              {
                method: fortune.methods.create,
                type: 'postTag',
                payload: [postTag]
              }).then(result => {
              console.log(result)
            }).catch(err => {
              console.log(err)
            })

          }
        }

      })
    })
  },
  listPosts: function(){
    store.find('post').then(results => {
      var p = results.payload.records 
      var ids = []
      for(var i = 0; i < p.length; i++){
        ids.push(p[i].id)
      }
      //console.log(ids)
      return ids
    }).then(asdf => {
      console.log(asdf)
    })
  }
}

data.generatePostTags()
//data.listPosts()
//data.generateTags()
/*
store.request(
  {
    method: fortune.methods.create,
    type: 'post',
    payload: [{title: 'hello, world', OC: false}]
  }).then(result => {
  console.log(result)
})

*/
